// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TFinal.Context;

#nullable disable

namespace TFinal.Migrations
{
    [DbContext(typeof(InmuebleContext))]
    partial class InmuebleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TFinal.Models.Cliente", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cliente"));

                    b.Property<string>("correo_cliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dir_cliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nombre_cliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("telefono_cliente")
                        .HasColumnType("int");

                    b.HasKey("id_cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TFinal.Models.Condicion", b =>
                {
                    b.Property<int>("id_condicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_condicion"));

                    b.Property<string>("des_condicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_condicion");

                    b.ToTable("Condiciones");
                });

            modelBuilder.Entity("TFinal.Models.Forma_Pago", b =>
                {
                    b.Property<int>("id_forma_pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_forma_pago"));

                    b.Property<string>("desc_forma_pago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_forma_pago");

                    b.ToTable("FormaPagos");
                });

            modelBuilder.Entity("TFinal.Models.Inmueble", b =>
                {
                    b.Property<int>("id_inmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_inmueble"));

                    b.Property<double>("costo_inmueble")
                        .HasColumnType("float");

                    b.Property<string>("desc_inmueble")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_tipo_inmueble")
                        .HasColumnType("int");

                    b.Property<string>("ubic_inmueble")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_inmueble");

                    b.ToTable("Inmuebles");
                });

            modelBuilder.Entity("TFinal.Models.Tipo_Inmueble", b =>
                {
                    b.Property<int>("id_tipo_inmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tipo_inmueble"));

                    b.Property<string>("desc_inmueble")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tipo_inmueble");

                    b.ToTable("TiposInmuebles");
                });

            modelBuilder.Entity("TFinal.Models.Venta", b =>
                {
                    b.Property<int>("id_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_venta"));

                    b.Property<string>("desc_venta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("fecha_venta")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<int>("id_condicion")
                        .HasColumnType("int");

                    b.Property<int>("id_forma_pago")
                        .HasColumnType("int");

                    b.Property<int>("id_inmueble")
                        .HasColumnType("int");

                    b.Property<int>("total_general")
                        .HasColumnType("int");

                    b.Property<int>("total_iva")
                        .HasColumnType("int");

                    b.Property<int>("total_venta")
                        .HasColumnType("int");

                    b.HasKey("id_venta");

                    b.ToTable("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
